kind = "web"
previewPath = "/"
title = "seina Website"
version = "1.0.0"
id = "artifacts/seina-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23878

[services.development]
run = "pnpm --filter @workspace/seina-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/seina-website", "run", "build" ]
publicDir = "artifacts/seina-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23878"
BASE_PATH = "/"
